/**
 * AI Vault Automated Factory v2.1
 * ─────────────────────────────────
 * Generates a new eBook product and syncs to Stripe / Ebook store.
 * Strictly isolated: NEVER writes to Amcal Roster DB (gcslfkujlfnznedatrsn).
 * Supports both dedicated Ebook Supabase instance and Local-First file storage.
 */

const Stripe = require('stripe');
const fs = require('fs');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '..', '.env') });

// ── Environment Variables (Ebook-specific) ───────────────────────────
const STRIPE_KEY = process.env.STRIPE_SECRET_KEY;
const SUPABASE_URL = process.env.EBOOK_SUPABASE_URL;
const SUPABASE_KEY = process.env.EBOOK_SUPABASE_SERVICE_ROLE_KEY || process.env.EBOOK_SUPABASE_KEY;
const STORAGE_BUCKET = process.env.EBOOK_STORAGE_BUCKET || 'ebook-vault';

if (!STRIPE_KEY) {
    console.error('[Factory] FATAL: Missing STRIPE_SECRET_KEY in environment.');
    process.exit(1);
}

const stripe = new Stripe(STRIPE_KEY);

// ── Topic Pool ──────────────────────────────────────────────────────
const topics = [
    'AI for Lawyers',
    'ChatGPT Prompts for Marketers',
    'Zero-Code Automation Playbook',
    'Mastering Midjourney V6',
    'AI in Real Estate',
    'Python + AI: The Ultimate Guide',
    'Scaling E-commerce with AI',
    'AI Content Creation Mastery',
];

function getRandomTopic() {
    return topics[Math.floor(Math.random() * topics.length)];
}

// ── File Delivery Handler (Supabase or Local-First Fallback) ────────
async function saveEbookFile(fileName, fileBuffer) {
    // If dedicated Ebook Supabase is configured and not the Roster DB
    if (SUPABASE_URL && SUPABASE_KEY && !SUPABASE_URL.includes('gcslfkujlfnznedatrsn')) {
        const url = `${SUPABASE_URL}/storage/v1/object/${STORAGE_BUCKET}/${fileName}`;
        const res = await fetch(url, {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${SUPABASE_KEY}`,
                'apikey': SUPABASE_KEY,
                'Content-Type': 'application/zip',
                'x-upsert': 'true',
            },
            body: fileBuffer,
        });

        if (!res.ok) {
            const errBody = await res.text();
            throw new Error(`Ebook Supabase Upload Error (${res.status}): ${errBody}`);
        }

        return `${SUPABASE_URL}/storage/v1/object/public/${STORAGE_BUCKET}/${fileName}`;
    }

    // Local-First Fallback: Store in src/downloads and public/downloads
    const srcDownloads = path.join(__dirname, '..', 'src', 'downloads');
    const publicDownloads = path.join(__dirname, '..', 'public', 'downloads');
    if (!fs.existsSync(srcDownloads)) fs.mkdirSync(srcDownloads, { recursive: true });
    if (!fs.existsSync(publicDownloads)) fs.mkdirSync(publicDownloads, { recursive: true });

    fs.writeFileSync(path.join(srcDownloads, fileName), fileBuffer);
    fs.writeFileSync(path.join(publicDownloads, fileName), fileBuffer);
    console.log(`[Factory] Saved eBook locally to downloads/${fileName}`);

    return `./downloads/${fileName}`;
}

// ── Main Factory ────────────────────────────────────────────────────
async function runFactory() {
    try {
        const topic = getRandomTopic();
        const id = topic.toLowerCase().replace(/[^a-z0-9]+/g, '-');
        const price = Math.floor(Math.random() * (20 - 9) + 9);

        console.log(`[Factory] Generating new eBook: "${topic}" ($${price})`);

        // 1. Create dummy product zip
        const zipContent = Buffer.from(
            `Exclusive content for: ${topic}\nGenerated by AI Vault Factory at ${new Date().toISOString()}`
        );

        // 2. Save via Ebook Storage handler
        const fileName = `${id}_${Date.now()}.zip`;
        const downloadUrl = await saveEbookFile(fileName, zipContent);
        console.log(`[Factory] Download URL established: ${downloadUrl}`);

        // 3. Create Stripe Product + Price
        const product = await stripe.products.create({
            name: topic,
            description: `A comprehensive guide on ${topic}. Claim your master key to unlock 100% of AI's potential.`,
        });

        const priceObj = await stripe.prices.create({
            product: product.id,
            unit_amount: price * 100,
            currency: 'usd',
        });

        // 4. Create Payment Link
        const redirectUrl = downloadUrl.startsWith('http') ? downloadUrl : `https://ebook-landing.vercel.app/${downloadUrl.replace('./', '')}`;
        const paymentLink = await stripe.paymentLinks.create({
            line_items: [{ price: priceObj.id, quantity: 1 }],
            after_completion: { type: 'redirect', redirect: { url: redirectUrl } },
        });
        console.log(`[Factory] Payment Link: ${paymentLink.url}`);

        // 5. Update products.json with deduplication & image cover
        const productsJsonPath = path.join(__dirname, '..', 'src', 'products.json');
        const publicProductsJsonPath = path.join(__dirname, '..', 'public', 'products.json');
        let products = [];
        if (fs.existsSync(productsJsonPath)) {
            products = JSON.parse(fs.readFileSync(productsJsonPath, 'utf8'));
        }

        const svgFilename = `cover_${id}.svg`;
        const imagePath = `./images/${svgFilename}`;

        const existingIndex = products.findIndex(p => p.id === id);
        const newProduct = {
            id,
            title: topic,
            description: `A comprehensive guide on ${topic}. Claim your master key to unlock 100% of AI's potential.`,
            price,
            paymentUrl: paymentLink.url,
            downloadUrl,
            image: imagePath,
            category: 'AI Business',
            rating: "4.9",
            reviews: 142
        };

        if (existingIndex >= 0) {
            products[existingIndex] = newProduct;
        } else {
            products.unshift(newProduct);
        }

        fs.writeFileSync(productsJsonPath, JSON.stringify(products, null, 2));
        if (fs.existsSync(path.dirname(publicProductsJsonPath))) {
            fs.writeFileSync(publicProductsJsonPath, JSON.stringify(products, null, 2));
        }
        console.log('[Factory] products.json deduplicated and updated successfully.');
        console.log('[Factory] Done ✅');

    } catch (e) {
        console.error('[Factory] Fatal Error:', e.message || e);
        process.exit(1);
    }
}

runFactory();
